services:

  dev:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspace

    command: sleep infinity

    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.4

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: algafood

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: